service: iTunes

custom:
  systemUrl: http://example.com/api/v1/

provider:
  name: aws
  stage: dev
  environment:
    REDIS_HOST: redis-cluster.u1q0qy.ng.0001.use1.cache.amazonaws.com
    REDIS_PORT: 6379
    LOCAL_REDIS: true